# Enable 256 colors, https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal
set -g default-terminal "tmux-256color"
set -ga terminal-features ",*:RGB"
# Some programs ignore the TERM variable & terminfo database and instead rely on COLORTERM.
setenv -g COLORTERM "truecolor"
set -ga terminal-features ",*:hyperlinks"

# Window numbers start at 1 instead of 0 to make switching easier
set -g base-index 1
set -g pane-base-index 1

# Allow customizing window names using bash precmd_functions
set -g allow-rename on

# Update prefix key to ctrl+z
unbind C-b
set -g prefix C-z
bind C-z send-prefix
